let suggestions = [
    "channel",
    "CodingLab",
   "CodingNepal",
    "Youtube",
   "Youtube Channel",
    "Blogger",
    "Bollwood",
   "Vlogger",
    "Vechiles",
    "Facebook",
    "Freelancer",
   "Facebook page",
    "Designer",
    "Developer",
   "Web Designer",
   "Web Developer",
    "Login Form in HTML & CSS",
    "How to learn Html & CSS",
   "How to learn Javascript",
    "How to become a Freelancer",
   "How to become a web designer",
   "How to start Gaming channel",
   "How to start youtube channel" , 
   "What does Html stands for",
   "What does CSS stands for?"
]